### ISSUE TITLE
GenericAxi4LiteSlave warning G0010 in bramHandler

### ISSUE THREAD

**Issue by ChienTeLi** [esa-tu-darmstadt/BlueAXI#6]
GenericAxi4LiteSlave is my favorite module recently, as it has helped me design so many AXI4-Lite IPs. When I tried to use bramHandler, a conflict occurred.

axiWriteSpecialRange cannot fire before axiReadSpecialRangeDelayed, and vice versa.
Although it's just a warning, I've promoted it to an error in my compilation environment.

Would the following modification be acceptable? I believe the behavior remains the same.

Instead of having separate rules:
```
addRules(readRules);
addRules(writeRules);
```
Using:
 ```
addRules(rJoinDescendingUrgency(readRules, writeRules));
```

I think this change should not cause the entire writeRules to be blocked when the conflict occurs.

**Comment by jahofmann** [comment]
Great to hear that you like the module.

BlueAXI should be more explicit about scheduling in a few locations like this one.

Are you willing/able to create a pull request? The changes seems reasonable.

**Comment by ChienTeLi** [comment]
Sure, thank you for accepting the request.
